import type {Metadata} from "next";
import {Geist, Geist_Mono, Lora} from "next/font/google";
import "./globals.css";
import {Providers} from "@/lib/Provider";
import {ToastContainer} from "react-toastify";
import UserProfile from "@/components/UserProfile/UserProfile";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const openSans = Geist_Mono({
    variable: "--font-open-sans",
})

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const lora = Lora({
    variable: "--font-lora",
    subsets: ["latin", "cyrillic"], // обязательно добавьте subsets
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en" className={`${lora.variable} ${geistSans.variable} ${geistMono.variable} h-full`}>
        <body className={'relative h-full'}>
        <ToastContainer/>
        <Providers>
            <UserProfile/>
            {children}
        </Providers>
        </body>
        </html>
    );
}
